import { Geist, Geist_Mono } from 'next/font/google';
import './globals.css';
// Custom Providers
import { ThemeProvider } from '@/components/providers/themeProvider';
// UI Components
import { Header } from '@/components/ui/header';

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
});

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
});

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
  return (
    <html lang='en' suppressHydrationWarning>
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        <ThemeProvider attribute='class' defaultTheme='system' enableSystem={true} disableTransitionOnChange={true}>
          <Header />
          {/* Main content */}
          {children}
        </ThemeProvider>
      </body>
    </html>
  );
}
